# Generated by Django 4.0.2 on 2022-02-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettercontent',
            old_name='message',
            new_name='content',
        ),
    ]
