# Generated by Django 4.0.2 on 2022-02-23 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_rename_message_newslettercontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercontent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 23, 14, 7, 56, 402046, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date_subscription',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 23, 14, 8, 5, 519466, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newslettercontent',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
