# Generated by Django 4.0.2 on 2022-02-26 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newslettercontent_date_subscriber_date_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
