# Generated by Django 4.0.2 on 2022-02-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='city',
        ),
    ]
