# Generated by Django 4.0.1 on 2022-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variant_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='sku',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
