# Generated by Django 4.0.1 on 2022-02-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productattributes_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattributes',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
    ]
