# Generated by Django 4.0.1 on 2022-02-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattributes_brand_productattributes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
    ]
